#!/usr/bin/env bash
# Bash script that configures an Nginx server so that
# /redirect_me is redirecting to another page.

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
redir="\\\tlocation /redirect_me {\n\t\t return 301 https://www.github.com/Cofucan;\n\t}\n"
sed -i "30i $redir" /etc/nginx/sites-available/default
service nginx restart
