#!/usr/bin/env bash
# Bash script that configures an Nginx server so that
# /redirect_me is redirecting to another page.

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
redir="\\\trewrite ^/redirect_me https://www.github.com/Cofucan permanent;"
sudo sed -i "/listen 80 default_server/a $redir" /etc/nginx/sites-available/default
service nginx restart
