#!/usr/bin/env bash
# Bash script that configures an Nginx server so have
# custom 404 page with a custom text

sudo apt-get -y update
sudo apt-get -y install nginx
echo Hello World! > /var/www/html/index.nginx-debian.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    location /redirect_me {
        return 301 https://www.github.com/Cofucan;
    }
}" > /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}" > /etc/nginx/sites-enabled/default

# sudo sed -i "56i error_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}\n" /etc/nginx/sites-available/default
sudo service nginx restart
