#!/usr/bin/env bash
# Bash script that configures an Nginx server so have
# custom 404 page with a custom text

sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo echo -e "Ceci n'est pas une page\n" | tee /var/www/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    location /redirect_me {
        return 301 https://www.github.com/Cofucan;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html/;
        internal;
    }
}" > /etc/nginx/sites-enabled/default

sudo service nginx restart
