#!/usr/bin/env bash
# This bash script modifies the `default` config file of an Nginx server to be able to listen on port 80

# Path to the Nginx configuration file
nginx_conf="/etc/nginx/sites-enabled/default"

# Replace the "listen 8080;" line
sed -i 's/^\s*listen 8080;/\tlisten 80;/g' "$nginx_conf"

# Replace the "listen [::]:8080 default_server ipv6only=on;" line
sed -i 's/^\s*listen \[::\]:8080 default_server ipv6only=on;/\tlisten [::]:80 default_server ipv6only=on;/g' "$nginx_conf"

# Restart nginx
service nginx restart
