#!/usr/bin/env bash
# This bash script modifies the `default` config file of an Nginx server to be able to listen on port 80
sed -i 's/^\s*listen 8080 default_server;/\tlisten 80;/g' /etc/nginx/sites-enabled/default
sed -i 's/^\s*listen \[::\]:8080 default_server ipv6only=on;/\tlisten [::]:80 default_server ipv6only=on;/g' /etc/nginx/sites-enabled/default
service nginx restart
kill -9 "$(cat /run/nginx.pid)"
