#!/usr/bin/env bash
# This script displays information about a file in the current directory.
filename="school"

if [ ! -e "$filename" ]; then
    echo "$filename file does not exist"
elif [[ ! -f "$filename" && ! -s "$filename" ]]; then
    echo "$filename file exists"
    echo "$filename file is empty"
elif [[ ! -f "$filename" && -s "$filename" ]]; then
    echo "$filename file exists"
    echo "$filename file is not empty"
elif [[ -f "$filename" && ! -s "$filename" ]]; then
    echo "$filename file exists"
    echo "$filename file is empty"
    echo "$filename is a regular file"
elif [[ -f "$filename" && -s "$filename" ]]; then
    echo "$filename file exists"
    echo "$filename file is not empty"
    echo "$filename is a regular file"
fi
